<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="terms_of_use.aspx.cs" Inherits="terms_of_use" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server"></asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <div class="breadcrumb-area">
        <div class="container-fluid">
            <ol class="breadcrumb breadcrumb-list">
                <li class="breadcrumb-item"><a href="default">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Terms of Use</a></li>
            </ol>
        </div>
    </div>
    <section class="about-area about-page-area ptb-50 pt-0">
        <div class="container-fluid">
            <div class="row about-page-wrap">
                <div class="col-md-12">
                    <div class="about-content ptb-20">
                        
                        <h3 class="title">Website Terms of Use</h3>
                        <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. </p>
<p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology {Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, Privacy Policy and Terms of Use for access or usage of our website: <a href="https://ezcarestore.com/"><b> www.ezcarestore.com</b></a>. </p>
<p>The domain name <a href="https://ezcarestore.com/"><b> www.ezcarestore.com</b></a> or (hereinafter referred to as "Website") is owned by M/s Zingool Technologies Private Limited, which is a registered company, having its head office at 135, Continental Building, Dr. Annie Besant Road, Worli, Mumbai, Maharashtra - 400018, India (hereinafter referred to as "Ez Care"). </p>
                       <h3 class="title mt-12"> In General </h3>
                        <p>Ez Care owns and operates the website with its full ownership & control. This document governs your relationship with Ez Care as a Customer/ Ez Partner. Access to and use of this website and the products and services available through this website (collectively, the "Services") are subject to the following terms, conditions, and notices {"Website Terms of Use"). By using the Services, you are agreeing to all of the website terms of use, as may be updated by us from time to time. You should check this page regularly to take notice of any changes we may have made to the website terms of use. </p>
<p>Access to this website is permitted on a temporary basis, and we reserve the right to withdraw or amend the Services without notice. We will not be liable if for any reason this website is unavailable at any time or for any period. From time to time, we may restrict access to some parts or this entire website. </p>

                        <h3 class="title mt-12">Website disclaimer</h3>
                        <p>The contents of this website are only for information purpose. Users are advised to rely on information posted herein for any purpose only after verification and confirmation of the same from authentic and authoritative sources. Neither Ez Care nor the website developer is responsible for any consequences that may arise out of using such information without verification/ confirmation. There may be time gap in internet/ online posting/ transmission of information and availability of such information at browsers' end. Exact status may be confirmed from source <a href="https://ezcarestore.com/"><b> www.ezcarestore.com</b></a>. We are running this website, to promote our business within our direct selling network. We are at 135, Continental Building, Dr. Annie Besant Road, Worli, Mumbai, Maharashtra - 400018, India. The Payment Gateway, which we mentioned in this website, is our official account, the money collected from this website on behalf of Ez Care i.e. M/s Zingool Technologies Private Limited on the sale of products exclusively marketed by M/s Zingool Technologies Private Limited. </p>
                        <h3 class="title mt-12">Prohibitions</h3>
                        <p>he services available on this website are for customers, who are interested and have requested to become a Customer/ Ez Partner of the Ez Care. Once you register as a user, you will permit us to fill Ez Care registration form and to mention your name where ever your signature is required. 
You must not misuse this website: <a href="https://ezcarestore.com/"><b> www.ezcarestore.com</b></a>. You will not: commit or encourage a criminal offense; transmit or distribute a virus, trojan, worm, logic bomb or any other material which is malicious, technologically harmful, in breach of confidence or in any way offensive or obscene; hack into any aspect of the service; corrupt data; cause annoyance to other users; infringe upon the rights of any other.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <style>
        .about-page-wrap .about-content .title {
            font-size: 22px;
            line-height: 1.3;
            margin-bottom: 5px;
            /* max-width: 500px; */
            color: #323232;
            font-weight: 500;
            /* font-family: alex brush,cursive; */
            text-transform: capitalize;
        }


        /*   .about-page-wrap .about-thumb img {
            width: 100%;
        }*/

        .about-page-wrap {
            -webkit-box-align: center;
            -ms-flex-align: center;
            align-items: center;
            /*box-shadow: -15px 0 35px rgba(0, 0, 0, 0.1), 0 -15px 35px rgba(0, 0, 0, 0.1), 0 15px 35px rgba(0, 0, 0, 0.1);*/
                box-shadow: -20px 19px 35px rgba(0, 0, 0, 0.1), 20px 7px 20px 0px rgba(0, 0, 0, 0.1), 0 15px 6px rgba(0, 0, 0, 0.1);
        }

            .about-page-wrap .about-content {
                /*margin-right: -30px;*/
                padding-left: 40px;
            }



                .about-page-wrap .about-content p {
                    font-size: 16px;
                    margin-bottom: 20px;
                    text-align: justify;
                }
    </style>
</asp:Content>

